# Netlify configuration file
[build]
  publish = "dist"
  command = "npm run build"

# Redirects and headers
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist"